spring:
  data.rest.detection-strategy: annotated
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
  datasource:
    username: sa
    password: passord
    driverClassName: org.h2.Driver
  h2.console:
    enabled: true
    path: /h2
