  spring.datasource.url=jdbc:mariadb://tuverudnet02.mysql.domeneshop.no
  spring.datasource.username=tuverudnet02  
  spring.datasource.password=4-4lyste-DI-ffff
  spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDB105Dialect
  spring.jpa.hibernate.ddl-auto=create-drop